### ISSUE TITLE
ORA-00932 error occurs when logging in using LDAP credentials

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#57]
**Preconditions:**
* Use Oracle Database

**Steps to reproduce:**
1. Start the application server.
2. Log in using credentials of an LDAP user.

**Expected Result:** A user can log in using LDAP credentials.
**Actual Result:** The following error occurs:
```
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba23): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00932: несовместимые типы данных: ожидается -, получено CLOB
Error Code: 932
Call: SELECT DISTINCT t1.ID, t1.RULE_TYPE, t1.CREATE_TS, t1.CREATED_BY, t1.DELETE_TS, t1.DELETED_BY, t1.DESCRIPTION, t1.IS_OVERRIDE_EXIST_ACCESS_GRP, t1.IS_OVERRIDE_EXISTING_ROLES, t1.IS_TERMINAL_RULE, t1.UPDATE_TS, t1.UPDATED_BY, t1.VERSION, t1.ACCESS_GROUP_ID, t1.MATCHING_RULE_ORDER_ID, t1.MATCHING_RULE_STATUS_ID, t1.STRING_CONDITION, t0.ID, t0.CREATE_TS, t0.CREATED_BY, t0.IS_DEFAULT_ROLE, t0.DELETE_TS, t0.DELETED_BY, t0.DESCRIPTION, t0.LOC_NAME, t0.NAME, t0.ROLE_TYPE, t0.UPDATE_TS, t0.UPDATED_BY, t0.VERSION, t2.ID, t2.CREATE_TS, t2.CREATED_BY, t2.CUSTOM_MATCHING_RULE_ID, t2.DELETE_TS, t2.DELETED_BY, t2.ORDER_, t2.UPDATE_TS, t2.UPDATED_BY, t2.VERSION, t3.ID, t3.CREATE_TS, t3.CREATED_BY, t3.CUSTOM_MATCHING_RULE_ID, t3.DELETE_TS, t3.DELETED_BY, t3.IS_ACTIVE, t3.UPDATE_TS, t3.UPDATED_BY, t3.VERSION, t4.ID, t4.CREATE_TS, t4.CREATED_BY, t4.DELETE_TS, t4.DELETED_BY, t4.NAME, t4.UPDATE_TS, t4.UPDATED_BY, t4.VERSION, t4.PARENT_ID FROM LDAP_MATCHING_RULE t1 LEFT OUTER JOIN (LDAP_MATCHING_RULE_ROLE_LINK t5 JOIN SEC_ROLE t0 ON (t0.ID = t5.ROLE_ID)) ON (t5.MATCHING_RULE_ID = t1.ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_ORDER t2 ON (t2.ID = t1.MATCHING_RULE_ORDER_ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_STATUS t3 ON (t3.ID = t1.MATCHING_RULE_STATUS_ID) LEFT OUTER JOIN SEC_GROUP t4 ON (t4.ID = t1.ACCESS_GROUP_ID) WHERE (t1.DELETE_TS IS NULL)
Query: ReadAllQuery(referenceClass=AbstractDbStoredMatchingRule sql="SELECT DISTINCT t1.ID, t1.RULE_TYPE, t1.CREATE_TS, t1.CREATED_BY, t1.DELETE_TS, t1.DELETED_BY, t1.DESCRIPTION, t1.IS_OVERRIDE_EXIST_ACCESS_GRP, t1.IS_OVERRIDE_EXISTING_ROLES, t1.IS_TERMINAL_RULE, t1.UPDATE_TS, t1.UPDATED_BY, t1.VERSION, t1.ACCESS_GROUP_ID, t1.MATCHING_RULE_ORDER_ID, t1.MATCHING_RULE_STATUS_ID, t1.STRING_CONDITION, t0.ID, t0.CREATE_TS, t0.CREATED_BY, t0.IS_DEFAULT_ROLE, t0.DELETE_TS, t0.DELETED_BY, t0.DESCRIPTION, t0.LOC_NAME, t0.NAME, t0.ROLE_TYPE, t0.UPDATE_TS, t0.UPDATED_BY, t0.VERSION, t2.ID, t2.CREATE_TS, t2.CREATED_BY, t2.CUSTOM_MATCHING_RULE_ID, t2.DELETE_TS, t2.DELETED_BY, t2.ORDER_, t2.UPDATE_TS, t2.UPDATED_BY, t2.VERSION, t3.ID, t3.CREATE_TS, t3.CREATED_BY, t3.CUSTOM_MATCHING_RULE_ID, t3.DELETE_TS, t3.DELETED_BY, t3.IS_ACTIVE, t3.UPDATE_TS, t3.UPDATED_BY, t3.VERSION, t4.ID, t4.CREATE_TS, t4.CREATED_BY, t4.DELETE_TS, t4.DELETED_BY, t4.NAME, t4.UPDATE_TS, t4.UPDATED_BY, t4.VERSION, t4.PARENT_ID FROM LDAP_MATCHING_RULE t1 LEFT OUTER JOIN (LDAP_MATCHING_RULE_ROLE_LINK t5 JOIN SEC_ROLE t0 ON (t0.ID = t5.ROLE_ID)) ON (t5.MATCHING_RULE_ID = t1.ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_ORDER t2 ON (t2.ID = t1.MATCHING_RULE_ORDER_ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_STATUS t3 ON (t3.ID = t1.MATCHING_RULE_STATUS_ID) LEFT OUTER JOIN SEC_GROUP t4 ON (t4.ID = t1.ACCESS_GROUP_ID) WHERE (t1.DELETE_TS IS NULL)")
    at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382)
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
    at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
    at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:658)
    at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:342)
    at com.haulmont.addon.ldap.core.dao.MatchingRuleDao.getMatchingRules(MatchingRuleDao.java:85)
    at com.haulmont.addon.ldap.core.dao.MatchingRuleDao$$FastClassBySpringCGLIB$$a3e6d2be.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
    at com.haulmont.cuba.core.sys.TransactionalInterceptor.aroundInvoke(TransactionalInterceptor.java:55)
    at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
    at com.haulmont.addon.ldap.core.dao.MatchingRuleDao$$EnhancerBySpringCGLIB$$b846a03.getMatchingRules(<generated>)
    at com.haulmont.addon.ldap.core.service.UserSynchronizationServiceBean.synchronizeUser(UserSynchronizationServiceBean.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
    at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
    at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
    at com.sun.proxy.$Proxy273.synchronizeUser(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
    at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
    at com.sun.proxy.$Proxy60.synchronizeUser(Unknown Source)
    at com.haulmont.addon.ldap.web.security.ldapcomponent.LdapAddonLoginProvider.login(LdapAddonLoginProvider.java:74)
    at com.haulmont.cuba.web.security.ConnectionImpl.loginInternal(ConnectionImpl.java:190)
    at com.haulmont.cuba.web.security.ConnectionImpl.login(ConnectionImpl.java:89)
    at com.haulmont.cuba.web.app.loginwindow.AppLoginWindow.doLogin(AppLoginWindow.java:342)
    at com.haulmont.cuba.web.app.loginwindow.AppLoginWindow.doLogin(AppLoginWindow.java:311)
    at com.haulmont.cuba.web.app.loginwindow.AppLoginWindow.login(AppLoginWindow.java:257)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:92)
    at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:45)
    at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
    at com.vaadin.ui.Button.fireClick(Button.java:377)
    at com.haulmont.cuba.web.toolkit.ui.CubaButton.fireClick(CubaButton.java:54)
    at com.vaadin.ui.Button$1.click(Button.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:444)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:409)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
    at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312)
    at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
    at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
    at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba23): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00932: несовместимые типы данных: ожидается -, получено CLOB
Error Code: 932
Call: SELECT DISTINCT t1.ID, t1.RULE_TYPE, t1.CREATE_TS, t1.CREATED_BY, t1.DELETE_TS, t1.DELETED_BY, t1.DESCRIPTION, t1.IS_OVERRIDE_EXIST_ACCESS_GRP, t1.IS_OVERRIDE_EXISTING_ROLES, t1.IS_TERMINAL_RULE, t1.UPDATE_TS, t1.UPDATED_BY, t1.VERSION, t1.ACCESS_GROUP_ID, t1.MATCHING_RULE_ORDER_ID, t1.MATCHING_RULE_STATUS_ID, t1.STRING_CONDITION, t0.ID, t0.CREATE_TS, t0.CREATED_BY, t0.IS_DEFAULT_ROLE, t0.DELETE_TS, t0.DELETED_BY, t0.DESCRIPTION, t0.LOC_NAME, t0.NAME, t0.ROLE_TYPE, t0.UPDATE_TS, t0.UPDATED_BY, t0.VERSION, t2.ID, t2.CREATE_TS, t2.CREATED_BY, t2.CUSTOM_MATCHING_RULE_ID, t2.DELETE_TS, t2.DELETED_BY, t2.ORDER_, t2.UPDATE_TS, t2.UPDATED_BY, t2.VERSION, t3.ID, t3.CREATE_TS, t3.CREATED_BY, t3.CUSTOM_MATCHING_RULE_ID, t3.DELETE_TS, t3.DELETED_BY, t3.IS_ACTIVE, t3.UPDATE_TS, t3.UPDATED_BY, t3.VERSION, t4.ID, t4.CREATE_TS, t4.CREATED_BY, t4.DELETE_TS, t4.DELETED_BY, t4.NAME, t4.UPDATE_TS, t4.UPDATED_BY, t4.VERSION, t4.PARENT_ID FROM LDAP_MATCHING_RULE t1 LEFT OUTER JOIN (LDAP_MATCHING_RULE_ROLE_LINK t5 JOIN SEC_ROLE t0 ON (t0.ID = t5.ROLE_ID)) ON (t5.MATCHING_RULE_ID = t1.ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_ORDER t2 ON (t2.ID = t1.MATCHING_RULE_ORDER_ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_STATUS t3 ON (t3.ID = t1.MATCHING_RULE_STATUS_ID) LEFT OUTER JOIN SEC_GROUP t4 ON (t4.ID = t1.ACCESS_GROUP_ID) WHERE (t1.DELETE_TS IS NULL)
Query: ReadAllQuery(referenceClass=AbstractDbStoredMatchingRule sql="SELECT DISTINCT t1.ID, t1.RULE_TYPE, t1.CREATE_TS, t1.CREATED_BY, t1.DELETE_TS, t1.DELETED_BY, t1.DESCRIPTION, t1.IS_OVERRIDE_EXIST_ACCESS_GRP, t1.IS_OVERRIDE_EXISTING_ROLES, t1.IS_TERMINAL_RULE, t1.UPDATE_TS, t1.UPDATED_BY, t1.VERSION, t1.ACCESS_GROUP_ID, t1.MATCHING_RULE_ORDER_ID, t1.MATCHING_RULE_STATUS_ID, t1.STRING_CONDITION, t0.ID, t0.CREATE_TS, t0.CREATED_BY, t0.IS_DEFAULT_ROLE, t0.DELETE_TS, t0.DELETED_BY, t0.DESCRIPTION, t0.LOC_NAME, t0.NAME, t0.ROLE_TYPE, t0.UPDATE_TS, t0.UPDATED_BY, t0.VERSION, t2.ID, t2.CREATE_TS, t2.CREATED_BY, t2.CUSTOM_MATCHING_RULE_ID, t2.DELETE_TS, t2.DELETED_BY, t2.ORDER_, t2.UPDATE_TS, t2.UPDATED_BY, t2.VERSION, t3.ID, t3.CREATE_TS, t3.CREATED_BY, t3.CUSTOM_MATCHING_RULE_ID, t3.DELETE_TS, t3.DELETED_BY, t3.IS_ACTIVE, t3.UPDATE_TS, t3.UPDATED_BY, t3.VERSION, t4.ID, t4.CREATE_TS, t4.CREATED_BY, t4.DELETE_TS, t4.DELETED_BY, t4.NAME, t4.UPDATE_TS, t4.UPDATED_BY, t4.VERSION, t4.PARENT_ID FROM LDAP_MATCHING_RULE t1 LEFT OUTER JOIN (LDAP_MATCHING_RULE_ROLE_LINK t5 JOIN SEC_ROLE t0 ON (t0.ID = t5.ROLE_ID)) ON (t5.MATCHING_RULE_ID = t1.ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_ORDER t2 ON (t2.ID = t1.MATCHING_RULE_ORDER_ID) LEFT OUTER JOIN LDAP_MATCHING_RULE_STATUS t3 ON (t3.ID = t1.MATCHING_RULE_STATUS_ID) LEFT OUTER JOIN SEC_GROUP t4 ON (t4.ID = t1.ACCESS_GROUP_ID) WHERE (t1.DELETE_TS IS NULL)")
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:702)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:544)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2052)
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:258)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.executeCall(ExpressionQueryMechanism.java:2863)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2751)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2704)
    at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1172)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1801)
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
    ... 120 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00932: несовместимые типы данных: ожидается -, получено CLOB
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)
    at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
    at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)
    at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
    at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
    at com.haulmont.cuba.core.sys.jdbc.ProxyPreparedStatement.lambda$executeQuery$0(ProxyPreparedStatement.java:34)
    at com.haulmont.cuba.core.sys.jdbc.ProxyStatement.executeSqlStatement(ProxyStatement.java:257)
    at com.haulmont.cuba.core.sys.jdbc.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:34)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1040)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:659)
    ... 142 more
```

**Comment by smianna** [comment]
Verified
